
name: Github pages deploy

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.0

    - run: yarn build 

